name       : transmission
version    : 4.0.4
release    : 24
source     :
    - https://github.com/transmission/transmission/releases/download/4.0.4/transmission-4.0.4.tar.xz : 15f7b4318fdfbffb19aa8d9a6b0fd89348e6ef1e86baa21a0806ffd1893bd5a6
homepage   : https://transmissionbt.com/
license    : GPL-2.0-or-later
component  : network.download
summary    : Lightweight BitTorrent client
description: |
    Transmission provides a simple and easy to use cross-platform lightweight BitTorrent client
networking : yes # check
builddeps  :
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libcurl)
    - pkgconfig(libevent)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build

    # Create a service without the user set
    sed '/^User/d' daemon/transmission-daemon.service > transmission-daemon.service
install    : |
    %ninja_install

    install -Dm00644 -t $installdir/%libdir%/systemd/user transmission-daemon.service

    rm -rf $installdir/usr/share/doc/transmission/news
check      : |
    %ninja_check
